bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),

]

hearne_photos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('photos/', include('photos.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.photos, name='photos'),
    path('photos_other/', views.photos_other, name='photos_other'),
    path('photos_ne/', views.photos_ne, name='photos_ne'),
    path('<int:photo_id>/', views.photo_detail, name='photo_detail'),
    path('add/', views.add_photo, name='add_photo'),
    path('edit/<int:photo_id>/', views.edit_photo, name='edit_photo'),
    path('delete/<int:photo_id>/', views.delete_photo, name='delete_photo'),


]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField

from photos.models import Photo
from profiles.models import UserProfile

# Create your models here.


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.BigIntegerField(default=0)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6,
                                        decimal_places=2,
                                        null=False, default=0)
    order_total = models.DecimalField(max_digits=10,
                                      decimal_places=2,
                                      null=False, default=0)
    grand_total = models.DecimalField(max_digits=10,
                                      decimal_places=2,
                                      null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254,
                                  null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate((
            Sum('lineitem_total')))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * (
                settings.STANDARD_DELIVERY_PERCENTAGE) / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineitems')
    photo = models.ForeignKey(Photo, null=False, blank=False,
                              on_delete=models.CASCADE)
    photo_size = models.CharField(max_length=5)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6,
                                         decimal_places=2, null=False,
                                         blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.photo.price * self.quantity
        super().save(*args, **kwargs)

photos/models.py
from django.db import models

# Create your models here.


class Photo(models.Model):

    class meta:
        verbose_name = 'Photos'

    Location = models.CharField(max_length=100)
    desc = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    img = models.ImageField(upload_to='')
    NE = models.BooleanField(default=True)

photos/forms.py
from django import forms

from .models import Photo


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('Location', 'desc', 'price',
                  'has_sizes', 'img',
                  'NE',)

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field
        """

        super().__init__(*args, **kwargs)
        placeholders = {
            'Location': 'Location',
            'desc': 'Description',
            'price': 'Price',
            'has_sizes': 'Size',
            'img': 'Photo',
            'NE': 'NE',
        }

photos/views.py
from django.shortcuts import (
    render, redirect, reverse, get_object_or_404)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
from .models import Photo
from .forms import PhotoForm

# Create your views here.


def photos(request):
    """ A view to return all photos page including the user searching """

    photos = Photo.objects.all()
    query = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                photos = photos.annotate(lower_name=Lower('name'))

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            photos = photos.order_by(sortkey)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, (
                    "You didn't enter any search criteria!"))
                return redirect(reverse('photos'))

            queries = Q(Location__icontains=query) | (
                Q(desc__icontains=query))
            photos = photos.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
       'photos': photos,
       'search_term': query,
       'current_sorting': current_sorting,

    }

    return render(request, 'photos/photos.html', context)


def photos_other(request):
    """ A view to return all photos page including the user searching """

    photos = Photo.objects.all()
    query = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                photos = photos.annotate(lower_name=Lower('name'))

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            photos = photos.order_by(sortkey)

        if 'NE' in request.GET:
            photos = Photo.objects.filter(NE=False)

    current_sorting = f'{sort}_{direction}'

    context = {
       'photos': photos,
       'search_term': query,
       'current_sorting': current_sorting,

    }

    return render(request, 'photos/photos_other.html', context)


def photos_ne(request):
    """ A view to return all photos page including the user searching """

    photos = Photo.objects.all()
    query = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                photos = photos.annotate(lower_name=Lower('name'))

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            photos = photos.order_by(sortkey)

        if 'NE' in request.GET:
            photos = Photo.objects.filter(NE=True)

    current_sorting = f'{sort}_{direction}'

    context = {
       'photos': photos,
       'search_term': query,
       'current_sorting': current_sorting,

    }

    return render(request, 'photos/photos_ne.html', context)


def photo_detail(request, photo_id):
    """ A view to show certain photo information"""

    photo = get_object_or_404(Photo, pk=photo_id)

    context = {
       'photo': photo,
    }

    return render(request, 'photos/photo_detail.html', context)


@login_required
def add_photo(request):
    """ Add a photo to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save()
            form.save()
            messages.success(request, 'Successfully added photo!')
            return redirect(reverse('photo_detail', args=[photo.id]))
        else:
            messages.error(request, (
                'Failed to add photo. Please ensure the form is valid.'))
    else:
        form = PhotoForm()
    template = 'photos/add_photo.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_photo(request, photo_id):
    """ Edit a photo in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    photo = get_object_or_404(Photo, pk=photo_id)
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES, instance=photo)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated photo!')
            return redirect(reverse('photo_detail', args=[photo.id]))
        else:
            messages.error(request, (
                'Failed to update photo. Please ensure the form is valid.'))
    else:
        form = PhotoForm(instance=photo)
        messages.info(request, f'You are editing {photo.Location}')

    template = 'photos/edit_photo.html'
    context = {
        'form': form,
        'photo': photo,
    }

    return render(request, template, context)


@login_required
def delete_photo(request, photo_id):
    """ Delete a photo from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))
    photo = get_object_or_404(Photo, pk=photo_id)
    photo.delete()
    messages.success(request, 'Photo deleted!')
    return redirect(reverse('photos'))

photos/templates/photos/add_photo.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <!--titles-->
                <hr>
                <h2 class="logo-font mb-4">Photo Management</h2>
                <h5 class="text-muted">Add a Photo</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <!--button to add photo-->
                <form method="POST" action="{% url 'add_photo' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'photos' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Add Photo</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

photos/templates/photos/edit_photo.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <!--titles-->
                <hr>
                <h2 class="logo-font mb-4">Photo Management</h2>
                <h5 class="text-muted">Edit a Photo</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <!--button to edit photos-->
                <form method="POST" action="{% url 'edit_photo' photo.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'photos' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Edit Photo</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

photos/templates/photos/photo_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
                <div class="image-container my-5">
                    <!--Will show the the photo's image and the photo location if it can not get the image-->
                    {% if photo.img %}
                        <a href="{{ photo.img.url }}" target="_blank">
                            <img class="card-img-top img-fluid" src="{{ photo.img.url }}" alt="{{ photo.Location }}">
                        </a>
                    {% else %}
                        <a href="">
                            <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ photo.Location }}">
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="photo-details-container mb-5 mt-md-5">
                    <h2 class="mb-0">{{ photo.Location }}</h2>
                    <br>
                    <p class="lead mb-0 text-left">Price: £{{ photo.price }}</p>
                    <br>
                    <p class="mt-3">{{ photo.desc }}</p>
                    <br>
                    <!--edit and delete photos buttons-->
                    {% if request.user.is_superuser %}
                        <small class="">
                            <a href="{% url 'edit_photo' photo.id %}">Edit</a> | 
                            <a class="text-danger" href="{% url 'delete_photo' photo.id %}">Delete</a>
                        </small>
                    {% endif %}
                    <br>
                    <!--Will be able to put items into the shopping bag using the post-->
                    <form class="form" action="{% url 'add_to_bag' photo.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            {% with photo.has_sizes as s %}
                            {% if s %}
                                <div class="col-12">
                                    <br>
                                    <p><strong>Size:</strong></p>
                                    <select class="form-control rounded-0 w-50" name="photo_size" id='id_photo_size'>
                                        <option value="4x6">4"x6"</option>
                                        <option value="5x7">5"x7"</option>
                                        <option value="8x10" selected>8"x10"</option>
                                        <option value="16x20">16"x20"</option>
                                        <option value="20x30">20"x30"</option>
                                    </select>
                                </div>
                            {% endif %}
                            <div class="col-12">
                                <p class="mt-3"><strong>Quantity:</strong></p>
                                <!--buttons to select quantity-->
                                <div class="form-group w-50">
                                    <div class="input-group">
                                        <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button class="decrement-qty btn btn-black rounded-0" 
                                                data-item_id="{{ photo.id }}" id="decrement-qty_{{ photo.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-minus"></i>
                                                </span>
                                            </button>
                                        </div>
                                        <input class="form-control qty_input" type="number"
                                            name="quantity" value="1" min="1" max="99"
                                            data-item_id="{{ photo.id }}"
                                            id="id_qty_{{ photo.id }}">
                                        <div class="input-group-append">
                                            <button class="increment-qty btn btn-black rounded-0"
                                                data-item_id="{{ photo.id }}" id="increment-qty_{{ photo.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-plus"></i>
                                                </span>
                                            </button>
                                        </div>
                                     </div>
                                 </div>
                            </div>
                            <!--button to keep browsing-->
                            <div class="col{% if s %}-12 mt-2{% endif %}">
                                <a href="{% url 'photos' %}" class="btn btn-outline-black rounded-0 mt-5">
                                    <span class="icon">
                                        <i class="fas fa-chevron-left"></i>
                                    </span>
                                    <span class="text-uppercase">Keep Browsing</span>
                                </a>
                                <input type="submit" class="btn btn-black rounded-0 text-uppercase mt-5" value="Add to Bag">
                            </div>
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                            {% endwith %}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
<!--this will load the quantity_input_script.html scripting -->
{% block postloadjs %}
{{ block.super }}
{% include 'photos/includes/quantity_input_script.html' %}
{% endblock %}

photos/templates/photos/photos.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col text-center mt-3">
                <!--titles-->
                <h2 class="logo-font">Photos</h2>
                <hr class="w-50 mb-2">
            </div>
        </div>
        <div class="row">
            <div class="photo-container col-10 offset-1">
                <div class="row mt-1 mb-2"></div>
                <div class="row mt-1 mb-2">
                    <div class="col-12 col-md-6 my-auto order-md-last d-flex justify-content-center justify-content-md-end">
                        <div class="sort-select-wrapper w-50">
                            <!--drop down box to sort the photos-->
                            <select id="sort-selector" class="custom-select custom-select-sm rounded-0 border border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
                                <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...</option>
                                <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price (low to high)</option>
                                <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price (high to low)</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-12 col-md-6 order-md-first">
                        <p class="text-muted mt-3 text-center text-md-left">
                            {% if search_term or current_categories or current_sorting != 'None_None' %}
                                <span class="small"><a href="{% url 'photos' %}">Reset</a> | </span>
                            {% endif %}
                            {{ photos|length }} Photos{% if search_term %} found for <strong>"{{ search_term }}"</strong>{% endif %}
                        </p>
                    </div>
                </div>
                <div class="row">
                    {% for photo in photos %}
                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                            <div class="card h-100 border-0">
                                <!--Will show the the photo's image and the photo location if it can not get the image-->
                                {% if photo.img %}
                                <a href="{% url 'photo_detail' photo.id %}">
                                    <img class="card-img-top img-fluid img-height" src="{{ photo.img.url }}" alt="{{ photo.Location }}">
                                </a>
                                {% else %}
                                <a href="{% url 'photo_detail' photo.id %}">
                                    <img class="card-img-top img-fluid img-height" src="{{ MEDIA_URL }}noimage.png" alt="{{ photo.Location }}">
                                </a>
                                {% endif %}
                                <!--Will show the photo name-->
                                <div class="card-body pb-0">
                                    <p class="mb-0 font-weight-bold">{{ photo.Location }}</p>
                                </div>
                                <!--Will show the photos price and description-->
                                <div class="card-footer bg-white pt-0 border-0 text-left">
                                    <div class="row">
                                        <div class="col">
                                            <p class="lead mb-0 text-left font-weight-bold">£{{ photo.price }}</p>
                                            <br>
                                            {% if request.user.is_superuser %}
                                                <small class="">
                                                    <a href="{% url 'edit_photo' photo.id %}">Edit</a> | 
                                                    <a class="text-danger" href="{% url 'delete_photo' photo.id %}">Delete</a>
                                                </small>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--Renders all of the coloumns so that when the page size is small less porducts will show-->
                        {% if forloop.counter|divisibleby:1 %}
                            <div class="col-12 d-sm-none mb-5">
                                <hr>
                            </div>
                        {% endif %}                        
                        {% if forloop.counter|divisibleby:2 %}
                            <div class="col-12 d-none d-sm-block d-md-block d-lg-none mb-5">
                                <hr>
                            </div>
                        {% endif %}
                        {% if forloop.counter|divisibleby:3 %}
                            <div class="col-12 d-none d-lg-block d-xl-none mb-5">
                                <hr>
                            </div>
                        {% endif %}
                        {% if forloop.counter|divisibleby:4 %}
                            <div class="col-12 d-none d-xl-block mb-5">
                                <hr>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="btt-button shadow-sm rounded-0 border border-black">
        <a class="btt-link d-flex h-100">
            <i class="fas fa-arrow-up text-black mx-auto my-auto"></i>
        </a>	
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
		$('.btt-link').click(function(e) {
			window.scrollTo(0,0)
		})
	</script>
    
    <script type="text/javascript">
        $('#sort-selector').change(function() {
            var selector = $(this);
            var currentUrl = new URL(window.location);

            var selectedVal = selector.val();
            if(selectedVal != "reset"){
                var sort = selectedVal.split("_")[0];
                var direction = selectedVal.split("_")[1];

                currentUrl.searchParams.set("sort", sort);
                currentUrl.searchParams.set("direction", direction);

                window.location.replace(currentUrl);
            } else {
                currentUrl.searchParams.delete("sort");
                currentUrl.searchParams.delete("direction");

                window.location.replace(currentUrl);
            }
        })
    </script>
{% endblock %}